ANONYMOUS_USER_ID = 1
ANONYMOUS_NICK = "anonymous"
RPP_POSTS = 2
TOP_VOTED_USERS_NUMBER = 10
ADMIN_USER = "admin"
ADMIN_PASSWORD = "duminit09"

MAX_NICK_LETTERS = 15
MAX_PASS_LETTERS = 15

MAX_POST_TITLE_LETTERS = 60
MIN_POST_TITLE_LETTERS = 1

MAX_POST_TEXT_LETTERS = 10000
MIN_POST_TEXT_LETTERS = 20

ANYTHING_TAG_ID = 1

APP_NAME = "MISTORIA"

