ANONYMOUS_USER_ID = 1
ANONYMOUS_NICK = "anonymous"
RPP_POSTS = 2
TOP_VOTED_USERS_NUMBER = 10
ADMIN_USER = "admin"
ADMIN_PASSWORD = "admin"

MAX_NICK_LETTERS = 15
MAX_PASS_LETTERS = 15

APP_NAME = "MISTORIA"

